// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent_hooks.dart';
import 'api/ai_dictation.dart';
import 'api/clipboard.dart';
import 'api/git.dart';
import 'api/git_diff_blob.dart';
import 'api/git_explorer_status.dart';
import 'api/merman_viewer.dart';
import 'api/process.dart';
import 'api/workspace_files.dart';
import 'api/workspace_search.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  dco_decode_StreamSink_agent_hook_event_batch_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<ProcessEvent> dco_decode_StreamSink_process_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SourceControlWatchSignal>
  dco_decode_StreamSink_source_control_watch_signal_Sse(dynamic raw);

  @protected
  RustStreamSink<WorkspaceExplorerWatchBatch>
  dco_decode_StreamSink_workspace_explorer_watch_batch_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentHookEndpointDto dco_decode_agent_hook_endpoint_dto(dynamic raw);

  @protected
  AgentHookEventBatchDto dco_decode_agent_hook_event_batch_dto(dynamic raw);

  @protected
  AgentHookEventDto dco_decode_agent_hook_event_dto(dynamic raw);

  @protected
  AiDictationError dco_decode_ai_dictation_error(dynamic raw);

  @protected
  AiDictationErrorKind dco_decode_ai_dictation_error_kind(dynamic raw);

  @protected
  AiDictationRequest dco_decode_ai_dictation_request(dynamic raw);

  @protected
  AiDictationResult dco_decode_ai_dictation_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiDictationRequest dco_decode_box_autoadd_ai_dictation_request(dynamic raw);

  @protected
  GitChangeArea dco_decode_box_autoadd_git_change_area(dynamic raw);

  @protected
  GitChangeEntry dco_decode_box_autoadd_git_change_entry(dynamic raw);

  @protected
  GitHistoryItemRef dco_decode_box_autoadd_git_history_item_ref(dynamic raw);

  @protected
  GitHistoryRefCategory dco_decode_box_autoadd_git_history_ref_category(
    dynamic raw,
  );

  @protected
  GitSubmoduleStatus dco_decode_box_autoadd_git_submodule_status(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SourceControlWatcherHandle
  dco_decode_box_autoadd_source_control_watcher_handle(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceExplorerDirectoryChildren
  dco_decode_box_autoadd_workspace_explorer_directory_children(dynamic raw);

  @protected
  WorkspaceExplorerWatcherHandle
  dco_decode_box_autoadd_workspace_explorer_watcher_handle(dynamic raw);

  @protected
  WorkspaceFileGitStatus dco_decode_box_autoadd_workspace_file_git_status(
    dynamic raw,
  );

  @protected
  WorkspaceQuickOpenSession dco_decode_box_autoadd_workspace_quick_open_session(
    dynamic raw,
  );

  @protected
  WorkspaceReplaceOptions dco_decode_box_autoadd_workspace_replace_options(
    dynamic raw,
  );

  @protected
  WorkspaceReplaceRequest dco_decode_box_autoadd_workspace_replace_request(
    dynamic raw,
  );

  @protected
  WorkspaceSearchOptions dco_decode_box_autoadd_workspace_search_options(
    dynamic raw,
  );

  @protected
  CodexSavedPrompt dco_decode_codex_saved_prompt(dynamic raw);

  @protected
  CodexSavedPromptScope dco_decode_codex_saved_prompt_scope(dynamic raw);

  @protected
  GitChangeArea dco_decode_git_change_area(dynamic raw);

  @protected
  GitChangeEntry dco_decode_git_change_entry(dynamic raw);

  @protected
  GitChangeGroup dco_decode_git_change_group(dynamic raw);

  @protected
  GitChangeStatus dco_decode_git_change_status(dynamic raw);

  @protected
  GitChangeTreeRow dco_decode_git_change_tree_row(dynamic raw);

  @protected
  GitChangeTreeRowKind dco_decode_git_change_tree_row_kind(dynamic raw);

  @protected
  GitCommitChangeEntry dco_decode_git_commit_change_entry(dynamic raw);

  @protected
  GitCommitCompareResult dco_decode_git_commit_compare_result(dynamic raw);

  @protected
  GitCommitCompareStatus dco_decode_git_commit_compare_status(dynamic raw);

  @protected
  GitCommitCompareSummary dco_decode_git_commit_compare_summary(dynamic raw);

  @protected
  GitDiffFile dco_decode_git_diff_file(dynamic raw);

  @protected
  GitDiffLine dco_decode_git_diff_line(dynamic raw);

  @protected
  GitDiffLineKind dco_decode_git_diff_line_kind(dynamic raw);

  @protected
  GitDiffResult dco_decode_git_diff_result(dynamic raw);

  @protected
  GitError dco_decode_git_error(dynamic raw);

  @protected
  GitErrorKind dco_decode_git_error_kind(dynamic raw);

  @protected
  GitExplorerStatus dco_decode_git_explorer_status(dynamic raw);

  @protected
  GitExplorerStatusEntry dco_decode_git_explorer_status_entry(dynamic raw);

  @protected
  GitExplorerStatusSnapshot dco_decode_git_explorer_status_snapshot(
    dynamic raw,
  );

  @protected
  GitHistoryItem dco_decode_git_history_item(dynamic raw);

  @protected
  GitHistoryItemRef dco_decode_git_history_item_ref(dynamic raw);

  @protected
  GitHistoryRefCategory dco_decode_git_history_ref_category(dynamic raw);

  @protected
  GitHistoryResult dco_decode_git_history_result(dynamic raw);

  @protected
  GitRangeCommit dco_decode_git_range_commit(dynamic raw);

  @protected
  GitRangeContext dco_decode_git_range_context(dynamic raw);

  @protected
  GitRangeFile dco_decode_git_range_file(dynamic raw);

  @protected
  GitRemote dco_decode_git_remote(dynamic raw);

  @protected
  GitRepositoryState dco_decode_git_repository_state(dynamic raw);

  @protected
  GitStashEntry dco_decode_git_stash_entry(dynamic raw);

  @protected
  GitStatusResult dco_decode_git_status_result(dynamic raw);

  @protected
  GitSubmoduleStatus dco_decode_git_submodule_status(dynamic raw);

  @protected
  GitWorktreeEntry dco_decode_git_worktree_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AgentHookEventDto> dco_decode_list_agent_hook_event_dto(dynamic raw);

  @protected
  List<CodexSavedPrompt> dco_decode_list_codex_saved_prompt(dynamic raw);

  @protected
  List<GitChangeEntry> dco_decode_list_git_change_entry(dynamic raw);

  @protected
  List<GitChangeGroup> dco_decode_list_git_change_group(dynamic raw);

  @protected
  List<GitChangeTreeRow> dco_decode_list_git_change_tree_row(dynamic raw);

  @protected
  List<GitCommitChangeEntry> dco_decode_list_git_commit_change_entry(
    dynamic raw,
  );

  @protected
  List<GitDiffFile> dco_decode_list_git_diff_file(dynamic raw);

  @protected
  List<GitDiffLine> dco_decode_list_git_diff_line(dynamic raw);

  @protected
  List<GitExplorerStatusEntry> dco_decode_list_git_explorer_status_entry(
    dynamic raw,
  );

  @protected
  List<GitHistoryItem> dco_decode_list_git_history_item(dynamic raw);

  @protected
  List<GitHistoryItemRef> dco_decode_list_git_history_item_ref(dynamic raw);

  @protected
  List<GitRangeCommit> dco_decode_list_git_range_commit(dynamic raw);

  @protected
  List<GitRangeFile> dco_decode_list_git_range_file(dynamic raw);

  @protected
  List<GitRemote> dco_decode_list_git_remote(dynamic raw);

  @protected
  List<GitStashEntry> dco_decode_list_git_stash_entry(dynamic raw);

  @protected
  List<GitWorktreeEntry> dco_decode_list_git_worktree_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<WorkspaceExplorerDirectoryChildren>
  dco_decode_list_workspace_explorer_directory_children(dynamic raw);

  @protected
  List<WorkspaceExplorerEntryBinding>
  dco_decode_list_workspace_explorer_entry_binding(dynamic raw);

  @protected
  List<WorkspaceExplorerTreeNode> dco_decode_list_workspace_explorer_tree_node(
    dynamic raw,
  );

  @protected
  List<WorkspaceFileEntry> dco_decode_list_workspace_file_entry(dynamic raw);

  @protected
  List<WorkspaceQuickOpenMatch> dco_decode_list_workspace_quick_open_match(
    dynamic raw,
  );

  @protected
  List<WorkspaceReplaceConflict> dco_decode_list_workspace_replace_conflict(
    dynamic raw,
  );

  @protected
  List<WorkspaceReplaceFileExpectation>
  dco_decode_list_workspace_replace_file_expectation(dynamic raw);

  @protected
  List<WorkspaceSearchFileResult> dco_decode_list_workspace_search_file_result(
    dynamic raw,
  );

  @protected
  List<WorkspaceSearchMatch> dco_decode_list_workspace_search_match(
    dynamic raw,
  );

  @protected
  MermanViewerError dco_decode_merman_viewer_error(dynamic raw);

  @protected
  MermanViewerErrorKind dco_decode_merman_viewer_error_kind(dynamic raw);

  @protected
  MermanWorkspaceRender dco_decode_merman_workspace_render(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GitChangeArea? dco_decode_opt_box_autoadd_git_change_area(dynamic raw);

  @protected
  GitChangeEntry? dco_decode_opt_box_autoadd_git_change_entry(dynamic raw);

  @protected
  GitHistoryItemRef? dco_decode_opt_box_autoadd_git_history_item_ref(
    dynamic raw,
  );

  @protected
  GitHistoryRefCategory? dco_decode_opt_box_autoadd_git_history_ref_category(
    dynamic raw,
  );

  @protected
  GitSubmoduleStatus? dco_decode_opt_box_autoadd_git_submodule_status(
    dynamic raw,
  );

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceExplorerDirectoryChildren?
  dco_decode_opt_box_autoadd_workspace_explorer_directory_children(dynamic raw);

  @protected
  WorkspaceFileGitStatus? dco_decode_opt_box_autoadd_workspace_file_git_status(
    dynamic raw,
  );

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ProcessEvent dco_decode_process_event(dynamic raw);

  @protected
  ProcessEventKind dco_decode_process_event_kind(dynamic raw);

  @protected
  ProcessRunResult dco_decode_process_run_result(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SourceControlWatchSignal dco_decode_source_control_watch_signal(dynamic raw);

  @protected
  SourceControlWatcherHandle dco_decode_source_control_watcher_handle(
    dynamic raw,
  );

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceEditorTextFile dco_decode_workspace_editor_text_file(dynamic raw);

  @protected
  WorkspaceExplorerDirectoryChildren
  dco_decode_workspace_explorer_directory_children(dynamic raw);

  @protected
  WorkspaceExplorerEntryBinding dco_decode_workspace_explorer_entry_binding(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerTreeNode dco_decode_workspace_explorer_tree_node(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerTreeNodeKind dco_decode_workspace_explorer_tree_node_kind(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerTreeProjection dco_decode_workspace_explorer_tree_projection(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerWatchBatch dco_decode_workspace_explorer_watch_batch(
    dynamic raw,
  );

  @protected
  WorkspaceExplorerWatcherHandle dco_decode_workspace_explorer_watcher_handle(
    dynamic raw,
  );

  @protected
  WorkspaceFileEntry dco_decode_workspace_file_entry(dynamic raw);

  @protected
  WorkspaceFileError dco_decode_workspace_file_error(dynamic raw);

  @protected
  WorkspaceFileErrorKind dco_decode_workspace_file_error_kind(dynamic raw);

  @protected
  WorkspaceFileGitStatus dco_decode_workspace_file_git_status(dynamic raw);

  @protected
  WorkspaceFileKind dco_decode_workspace_file_kind(dynamic raw);

  @protected
  WorkspaceQuickOpenMatch dco_decode_workspace_quick_open_match(dynamic raw);

  @protected
  WorkspaceQuickOpenSession dco_decode_workspace_quick_open_session(
    dynamic raw,
  );

  @protected
  WorkspaceReplaceConflict dco_decode_workspace_replace_conflict(dynamic raw);

  @protected
  WorkspaceReplaceFileExpectation dco_decode_workspace_replace_file_expectation(
    dynamic raw,
  );

  @protected
  WorkspaceReplaceOptions dco_decode_workspace_replace_options(dynamic raw);

  @protected
  WorkspaceReplacePreview dco_decode_workspace_replace_preview(dynamic raw);

  @protected
  WorkspaceReplaceRequest dco_decode_workspace_replace_request(dynamic raw);

  @protected
  WorkspaceReplaceResult dco_decode_workspace_replace_result(dynamic raw);

  @protected
  WorkspaceSearchError dco_decode_workspace_search_error(dynamic raw);

  @protected
  WorkspaceSearchErrorKind dco_decode_workspace_search_error_kind(dynamic raw);

  @protected
  WorkspaceSearchFileResult dco_decode_workspace_search_file_result(
    dynamic raw,
  );

  @protected
  WorkspaceSearchMatch dco_decode_workspace_search_match(dynamic raw);

  @protected
  WorkspaceSearchOptions dco_decode_workspace_search_options(dynamic raw);

  @protected
  WorkspaceSearchResult dco_decode_workspace_search_result(dynamic raw);

  @protected
  WorkspaceTextFile dco_decode_workspace_text_file(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AgentHookEventBatchDto>
  sse_decode_StreamSink_agent_hook_event_batch_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProcessEvent> sse_decode_StreamSink_process_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SourceControlWatchSignal>
  sse_decode_StreamSink_source_control_watch_signal_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WorkspaceExplorerWatchBatch>
  sse_decode_StreamSink_workspace_explorer_watch_batch_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentHookEndpointDto sse_decode_agent_hook_endpoint_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentHookEventBatchDto sse_decode_agent_hook_event_batch_dto(
    SseDeserializer deserializer,
  );

  @protected
  AgentHookEventDto sse_decode_agent_hook_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  AiDictationError sse_decode_ai_dictation_error(SseDeserializer deserializer);

  @protected
  AiDictationErrorKind sse_decode_ai_dictation_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  AiDictationRequest sse_decode_ai_dictation_request(
    SseDeserializer deserializer,
  );

  @protected
  AiDictationResult sse_decode_ai_dictation_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiDictationRequest sse_decode_box_autoadd_ai_dictation_request(
    SseDeserializer deserializer,
  );

  @protected
  GitChangeArea sse_decode_box_autoadd_git_change_area(
    SseDeserializer deserializer,
  );

  @protected
  GitChangeEntry sse_decode_box_autoadd_git_change_entry(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryItemRef sse_decode_box_autoadd_git_history_item_ref(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryRefCategory sse_decode_box_autoadd_git_history_ref_category(
    SseDeserializer deserializer,
  );

  @protected
  GitSubmoduleStatus sse_decode_box_autoadd_git_submodule_status(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SourceControlWatcherHandle
  sse_decode_box_autoadd_source_control_watcher_handle(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceExplorerDirectoryChildren
  sse_decode_box_autoadd_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerWatcherHandle
  sse_decode_box_autoadd_workspace_explorer_watcher_handle(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileGitStatus sse_decode_box_autoadd_workspace_file_git_status(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceQuickOpenSession sse_decode_box_autoadd_workspace_quick_open_session(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceOptions sse_decode_box_autoadd_workspace_replace_options(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceRequest sse_decode_box_autoadd_workspace_replace_request(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchOptions sse_decode_box_autoadd_workspace_search_options(
    SseDeserializer deserializer,
  );

  @protected
  CodexSavedPrompt sse_decode_codex_saved_prompt(SseDeserializer deserializer);

  @protected
  CodexSavedPromptScope sse_decode_codex_saved_prompt_scope(
    SseDeserializer deserializer,
  );

  @protected
  GitChangeArea sse_decode_git_change_area(SseDeserializer deserializer);

  @protected
  GitChangeEntry sse_decode_git_change_entry(SseDeserializer deserializer);

  @protected
  GitChangeGroup sse_decode_git_change_group(SseDeserializer deserializer);

  @protected
  GitChangeStatus sse_decode_git_change_status(SseDeserializer deserializer);

  @protected
  GitChangeTreeRow sse_decode_git_change_tree_row(SseDeserializer deserializer);

  @protected
  GitChangeTreeRowKind sse_decode_git_change_tree_row_kind(
    SseDeserializer deserializer,
  );

  @protected
  GitCommitChangeEntry sse_decode_git_commit_change_entry(
    SseDeserializer deserializer,
  );

  @protected
  GitCommitCompareResult sse_decode_git_commit_compare_result(
    SseDeserializer deserializer,
  );

  @protected
  GitCommitCompareStatus sse_decode_git_commit_compare_status(
    SseDeserializer deserializer,
  );

  @protected
  GitCommitCompareSummary sse_decode_git_commit_compare_summary(
    SseDeserializer deserializer,
  );

  @protected
  GitDiffFile sse_decode_git_diff_file(SseDeserializer deserializer);

  @protected
  GitDiffLine sse_decode_git_diff_line(SseDeserializer deserializer);

  @protected
  GitDiffLineKind sse_decode_git_diff_line_kind(SseDeserializer deserializer);

  @protected
  GitDiffResult sse_decode_git_diff_result(SseDeserializer deserializer);

  @protected
  GitError sse_decode_git_error(SseDeserializer deserializer);

  @protected
  GitErrorKind sse_decode_git_error_kind(SseDeserializer deserializer);

  @protected
  GitExplorerStatus sse_decode_git_explorer_status(
    SseDeserializer deserializer,
  );

  @protected
  GitExplorerStatusEntry sse_decode_git_explorer_status_entry(
    SseDeserializer deserializer,
  );

  @protected
  GitExplorerStatusSnapshot sse_decode_git_explorer_status_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryItem sse_decode_git_history_item(SseDeserializer deserializer);

  @protected
  GitHistoryItemRef sse_decode_git_history_item_ref(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryRefCategory sse_decode_git_history_ref_category(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryResult sse_decode_git_history_result(SseDeserializer deserializer);

  @protected
  GitRangeCommit sse_decode_git_range_commit(SseDeserializer deserializer);

  @protected
  GitRangeContext sse_decode_git_range_context(SseDeserializer deserializer);

  @protected
  GitRangeFile sse_decode_git_range_file(SseDeserializer deserializer);

  @protected
  GitRemote sse_decode_git_remote(SseDeserializer deserializer);

  @protected
  GitRepositoryState sse_decode_git_repository_state(
    SseDeserializer deserializer,
  );

  @protected
  GitStashEntry sse_decode_git_stash_entry(SseDeserializer deserializer);

  @protected
  GitStatusResult sse_decode_git_status_result(SseDeserializer deserializer);

  @protected
  GitSubmoduleStatus sse_decode_git_submodule_status(
    SseDeserializer deserializer,
  );

  @protected
  GitWorktreeEntry sse_decode_git_worktree_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AgentHookEventDto> sse_decode_list_agent_hook_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CodexSavedPrompt> sse_decode_list_codex_saved_prompt(
    SseDeserializer deserializer,
  );

  @protected
  List<GitChangeEntry> sse_decode_list_git_change_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GitChangeGroup> sse_decode_list_git_change_group(
    SseDeserializer deserializer,
  );

  @protected
  List<GitChangeTreeRow> sse_decode_list_git_change_tree_row(
    SseDeserializer deserializer,
  );

  @protected
  List<GitCommitChangeEntry> sse_decode_list_git_commit_change_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GitDiffFile> sse_decode_list_git_diff_file(SseDeserializer deserializer);

  @protected
  List<GitDiffLine> sse_decode_list_git_diff_line(SseDeserializer deserializer);

  @protected
  List<GitExplorerStatusEntry> sse_decode_list_git_explorer_status_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GitHistoryItem> sse_decode_list_git_history_item(
    SseDeserializer deserializer,
  );

  @protected
  List<GitHistoryItemRef> sse_decode_list_git_history_item_ref(
    SseDeserializer deserializer,
  );

  @protected
  List<GitRangeCommit> sse_decode_list_git_range_commit(
    SseDeserializer deserializer,
  );

  @protected
  List<GitRangeFile> sse_decode_list_git_range_file(
    SseDeserializer deserializer,
  );

  @protected
  List<GitRemote> sse_decode_list_git_remote(SseDeserializer deserializer);

  @protected
  List<GitStashEntry> sse_decode_list_git_stash_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GitWorktreeEntry> sse_decode_list_git_worktree_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceExplorerDirectoryChildren>
  sse_decode_list_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceExplorerEntryBinding>
  sse_decode_list_workspace_explorer_entry_binding(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceExplorerTreeNode> sse_decode_list_workspace_explorer_tree_node(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceFileEntry> sse_decode_list_workspace_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceQuickOpenMatch> sse_decode_list_workspace_quick_open_match(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceReplaceConflict> sse_decode_list_workspace_replace_conflict(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceReplaceFileExpectation>
  sse_decode_list_workspace_replace_file_expectation(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceSearchFileResult> sse_decode_list_workspace_search_file_result(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceSearchMatch> sse_decode_list_workspace_search_match(
    SseDeserializer deserializer,
  );

  @protected
  MermanViewerError sse_decode_merman_viewer_error(
    SseDeserializer deserializer,
  );

  @protected
  MermanViewerErrorKind sse_decode_merman_viewer_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  MermanWorkspaceRender sse_decode_merman_workspace_render(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GitChangeArea? sse_decode_opt_box_autoadd_git_change_area(
    SseDeserializer deserializer,
  );

  @protected
  GitChangeEntry? sse_decode_opt_box_autoadd_git_change_entry(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryItemRef? sse_decode_opt_box_autoadd_git_history_item_ref(
    SseDeserializer deserializer,
  );

  @protected
  GitHistoryRefCategory? sse_decode_opt_box_autoadd_git_history_ref_category(
    SseDeserializer deserializer,
  );

  @protected
  GitSubmoduleStatus? sse_decode_opt_box_autoadd_git_submodule_status(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceExplorerDirectoryChildren?
  sse_decode_opt_box_autoadd_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileGitStatus? sse_decode_opt_box_autoadd_workspace_file_git_status(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ProcessEvent sse_decode_process_event(SseDeserializer deserializer);

  @protected
  ProcessEventKind sse_decode_process_event_kind(SseDeserializer deserializer);

  @protected
  ProcessRunResult sse_decode_process_run_result(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SourceControlWatchSignal sse_decode_source_control_watch_signal(
    SseDeserializer deserializer,
  );

  @protected
  SourceControlWatcherHandle sse_decode_source_control_watcher_handle(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceEditorTextFile sse_decode_workspace_editor_text_file(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerDirectoryChildren
  sse_decode_workspace_explorer_directory_children(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerEntryBinding sse_decode_workspace_explorer_entry_binding(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerTreeNode sse_decode_workspace_explorer_tree_node(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerTreeNodeKind sse_decode_workspace_explorer_tree_node_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerTreeProjection sse_decode_workspace_explorer_tree_projection(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerWatchBatch sse_decode_workspace_explorer_watch_batch(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceExplorerWatcherHandle sse_decode_workspace_explorer_watcher_handle(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileEntry sse_decode_workspace_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileError sse_decode_workspace_file_error(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileErrorKind sse_decode_workspace_file_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileGitStatus sse_decode_workspace_file_git_status(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceFileKind sse_decode_workspace_file_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceQuickOpenMatch sse_decode_workspace_quick_open_match(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceQuickOpenSession sse_decode_workspace_quick_open_session(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceConflict sse_decode_workspace_replace_conflict(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceFileExpectation sse_decode_workspace_replace_file_expectation(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceOptions sse_decode_workspace_replace_options(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplacePreview sse_decode_workspace_replace_preview(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceRequest sse_decode_workspace_replace_request(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceReplaceResult sse_decode_workspace_replace_result(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchError sse_decode_workspace_search_error(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchErrorKind sse_decode_workspace_search_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchFileResult sse_decode_workspace_search_file_result(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchMatch sse_decode_workspace_search_match(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchOptions sse_decode_workspace_search_options(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceSearchResult sse_decode_workspace_search_result(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceTextFile sse_decode_workspace_text_file(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_agent_hook_event_batch_dto_Sse(
    RustStreamSink<AgentHookEventBatchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_process_event_Sse(
    RustStreamSink<ProcessEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_source_control_watch_signal_Sse(
    RustStreamSink<SourceControlWatchSignal> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_workspace_explorer_watch_batch_Sse(
    RustStreamSink<WorkspaceExplorerWatchBatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_hook_endpoint_dto(
    AgentHookEndpointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_hook_event_batch_dto(
    AgentHookEventBatchDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_agent_hook_event_dto(
    AgentHookEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_dictation_error(
    AiDictationError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_dictation_error_kind(
    AiDictationErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_dictation_request(
    AiDictationRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_dictation_result(
    AiDictationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_dictation_request(
    AiDictationRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_change_area(
    GitChangeArea self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_change_entry(
    GitChangeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_history_item_ref(
    GitHistoryItemRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_history_ref_category(
    GitHistoryRefCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_submodule_status(
    GitSubmoduleStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_control_watcher_handle(
    SourceControlWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_workspace_explorer_directory_children(
    WorkspaceExplorerDirectoryChildren self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_explorer_watcher_handle(
    WorkspaceExplorerWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_file_git_status(
    WorkspaceFileGitStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_quick_open_session(
    WorkspaceQuickOpenSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_replace_options(
    WorkspaceReplaceOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_replace_request(
    WorkspaceReplaceRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_workspace_search_options(
    WorkspaceSearchOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_codex_saved_prompt(
    CodexSavedPrompt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_codex_saved_prompt_scope(
    CodexSavedPromptScope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_change_area(GitChangeArea self, SseSerializer serializer);

  @protected
  void sse_encode_git_change_entry(
    GitChangeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_change_group(
    GitChangeGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_change_status(
    GitChangeStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_change_tree_row(
    GitChangeTreeRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_change_tree_row_kind(
    GitChangeTreeRowKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_commit_change_entry(
    GitCommitChangeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_commit_compare_result(
    GitCommitCompareResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_commit_compare_status(
    GitCommitCompareStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_commit_compare_summary(
    GitCommitCompareSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_diff_file(GitDiffFile self, SseSerializer serializer);

  @protected
  void sse_encode_git_diff_line(GitDiffLine self, SseSerializer serializer);

  @protected
  void sse_encode_git_diff_line_kind(
    GitDiffLineKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_diff_result(GitDiffResult self, SseSerializer serializer);

  @protected
  void sse_encode_git_error(GitError self, SseSerializer serializer);

  @protected
  void sse_encode_git_error_kind(GitErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_git_explorer_status(
    GitExplorerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_explorer_status_entry(
    GitExplorerStatusEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_explorer_status_snapshot(
    GitExplorerStatusSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_history_item(
    GitHistoryItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_history_item_ref(
    GitHistoryItemRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_history_ref_category(
    GitHistoryRefCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_history_result(
    GitHistoryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_range_commit(
    GitRangeCommit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_range_context(
    GitRangeContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_range_file(GitRangeFile self, SseSerializer serializer);

  @protected
  void sse_encode_git_remote(GitRemote self, SseSerializer serializer);

  @protected
  void sse_encode_git_repository_state(
    GitRepositoryState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_stash_entry(GitStashEntry self, SseSerializer serializer);

  @protected
  void sse_encode_git_status_result(
    GitStatusResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_submodule_status(
    GitSubmoduleStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_worktree_entry(
    GitWorktreeEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agent_hook_event_dto(
    List<AgentHookEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_codex_saved_prompt(
    List<CodexSavedPrompt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_change_entry(
    List<GitChangeEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_change_group(
    List<GitChangeGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_change_tree_row(
    List<GitChangeTreeRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_commit_change_entry(
    List<GitCommitChangeEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_diff_file(
    List<GitDiffFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_diff_line(
    List<GitDiffLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_explorer_status_entry(
    List<GitExplorerStatusEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_history_item(
    List<GitHistoryItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_history_item_ref(
    List<GitHistoryItemRef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_range_commit(
    List<GitRangeCommit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_range_file(
    List<GitRangeFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_remote(
    List<GitRemote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_stash_entry(
    List<GitStashEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_worktree_entry(
    List<GitWorktreeEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_explorer_directory_children(
    List<WorkspaceExplorerDirectoryChildren> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_explorer_entry_binding(
    List<WorkspaceExplorerEntryBinding> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_explorer_tree_node(
    List<WorkspaceExplorerTreeNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_file_entry(
    List<WorkspaceFileEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_quick_open_match(
    List<WorkspaceQuickOpenMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_replace_conflict(
    List<WorkspaceReplaceConflict> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_replace_file_expectation(
    List<WorkspaceReplaceFileExpectation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_search_file_result(
    List<WorkspaceSearchFileResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_search_match(
    List<WorkspaceSearchMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merman_viewer_error(
    MermanViewerError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merman_viewer_error_kind(
    MermanViewerErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merman_workspace_render(
    MermanWorkspaceRender self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_git_change_area(
    GitChangeArea? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_git_change_entry(
    GitChangeEntry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_git_history_item_ref(
    GitHistoryItemRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_git_history_ref_category(
    GitHistoryRefCategory? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_git_submodule_status(
    GitSubmoduleStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_workspace_explorer_directory_children(
    WorkspaceExplorerDirectoryChildren? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_workspace_file_git_status(
    WorkspaceFileGitStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_event(ProcessEvent self, SseSerializer serializer);

  @protected
  void sse_encode_process_event_kind(
    ProcessEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_run_result(
    ProcessRunResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_control_watch_signal(
    SourceControlWatchSignal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_control_watcher_handle(
    SourceControlWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_editor_text_file(
    WorkspaceEditorTextFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_directory_children(
    WorkspaceExplorerDirectoryChildren self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_entry_binding(
    WorkspaceExplorerEntryBinding self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_tree_node(
    WorkspaceExplorerTreeNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_tree_node_kind(
    WorkspaceExplorerTreeNodeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_tree_projection(
    WorkspaceExplorerTreeProjection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_watch_batch(
    WorkspaceExplorerWatchBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_explorer_watcher_handle(
    WorkspaceExplorerWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_entry(
    WorkspaceFileEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_error(
    WorkspaceFileError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_error_kind(
    WorkspaceFileErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_git_status(
    WorkspaceFileGitStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_file_kind(
    WorkspaceFileKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_quick_open_match(
    WorkspaceQuickOpenMatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_quick_open_session(
    WorkspaceQuickOpenSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_replace_conflict(
    WorkspaceReplaceConflict self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_replace_file_expectation(
    WorkspaceReplaceFileExpectation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_replace_options(
    WorkspaceReplaceOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_replace_preview(
    WorkspaceReplacePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_replace_request(
    WorkspaceReplaceRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_replace_result(
    WorkspaceReplaceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_search_error(
    WorkspaceSearchError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_search_error_kind(
    WorkspaceSearchErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_search_file_result(
    WorkspaceSearchFileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_search_match(
    WorkspaceSearchMatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_search_options(
    WorkspaceSearchOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_search_result(
    WorkspaceSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_text_file(
    WorkspaceTextFile self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
