//! Feeding an initial prompt to an agent whose CLI has no argument for one.
//!
//! `amp` is the only supported agent that cannot start interactively from a
//! prompt on its command line; it takes an opening message on stdin instead.
//! Redirecting stdin cannot be typed into the terminal, because the line goes
//! to whatever interactive shell the user configured and `<` is not something
//! PowerShell or nushell will run. So the redirect lives in a generated script
//! invoked by the one portable shape `worktree_setup_script` already
//! established, and the prompt itself lives in a plain file, where no shell
//! quoting can touch it.
//!
//! Only stdin is redirected. `amp` switches itself into non-interactive execute
//! mode when *stdout* is redirected, so leaving stdout and stderr on the PTY is
//! what keeps the agent in the tab after it answers.
//!
//! Neither file deletes itself. The script is still being read when it hands
//! over to the agent, and its redirect has to outlive that handover, so cleanup
//! is a startup sweep like the setup scripts use.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::worktree_setup_script::{invocation_line, make_executable, sanitize_script_id};

/// The generated pair and the line the terminal runs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentPromptStdinScript {
    pub script_path: PathBuf,
    pub prompt_path: PathBuf,
    pub command: String,
}

/// Prefix both generated files share, so one startup sweep clears both.
pub const AGENT_PROMPT_SCRIPT_PREFIX: &str = "agent-prompt-";

pub fn write_agent_prompt_stdin_script(
    directory: &Path,
    session_id: &str,
    command: &str,
    prompt: &str,
) -> Result<AgentPromptStdinScript> {
    let windows = cfg!(windows);
    let id = sanitize_script_id(session_id);
    let script_path = directory.join(format!(
        "{AGENT_PROMPT_SCRIPT_PREFIX}{id}.{}",
        script_extension(windows)
    ));
    let prompt_path = directory.join(format!("{AGENT_PROMPT_SCRIPT_PREFIX}{id}.txt"));
    std::fs::create_dir_all(directory)
        .with_context(|| format!("Could not create {}", directory.display()))?;
    std::fs::write(&prompt_path, prompt)
        .with_context(|| format!("Could not write {}", prompt_path.display()))?;
    let contents = if windows {
        windows_script(command, &prompt_path)
    } else {
        posix_script(command, &prompt_path)
    };
    std::fs::write(&script_path, contents)
        .with_context(|| format!("Could not write {}", script_path.display()))?;
    make_executable(&script_path)?;
    let command = invocation_line(&script_path, windows);
    Ok(AgentPromptStdinScript {
        script_path,
        prompt_path,
        command,
    })
}

/// Deletes every leftover prompt script and prompt file in `directory`.
///
/// Anything still there belongs to a previous host lifetime, so the terminal
/// that would have read it is already gone.
pub fn remove_stale_agent_prompt_scripts(directory: &Path) {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        if name.starts_with(AGENT_PROMPT_SCRIPT_PREFIX) {
            let _ = std::fs::remove_file(entry.path());
        }
    }
}

fn script_extension(windows: bool) -> &'static str {
    if windows {
        "cmd"
    } else {
        "sh"
    }
}

fn posix_script(command: &str, prompt_path: &Path) -> String {
    // `exec` replaces the shell, so the agent keeps the PTY's process slot and
    // the tab's termination sweep still reaches it as the shell's own child.
    format!(
        "#!/bin/sh\n# Generated by Alera. Do not edit.\nexec {} < {}\n",
        command.trim(),
        posix_quote(&prompt_path.display().to_string()),
    )
}

fn windows_script(command: &str, prompt_path: &Path) -> String {
    format!(
        "@echo off\r\nrem Generated by Alera. Do not edit.\r\n{} < \"{}\"\r\n",
        command.trim(),
        prompt_path.display(),
    )
}

/// Wraps in single quotes, which makes every other character inert in POSIX
/// shells, and closes/reopens the quoting around embedded single quotes.
fn posix_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn posix_script_execs_the_command_with_the_prompt_on_stdin() {
        assert_eq!(
            posix_script("amp --mode high", Path::new("/run/alera/agent-prompt-s1.txt")),
            "#!/bin/sh\n# Generated by Alera. Do not edit.\nexec amp --mode high < '/run/alera/agent-prompt-s1.txt'\n"
        );
    }

    #[test]
    fn posix_script_quotes_a_prompt_path_with_a_quote_in_it() {
        assert_eq!(
            posix_script("amp", Path::new("/run/it's/agent-prompt-s1.txt")),
            "#!/bin/sh\n# Generated by Alera. Do not edit.\nexec amp < '/run/it'\\''s/agent-prompt-s1.txt'\n"
        );
    }

    #[test]
    fn windows_script_redirects_without_exec() {
        assert_eq!(
            windows_script("amp --mode high", Path::new("C:\\a b\\agent-prompt-s1.txt")),
            "@echo off\r\nrem Generated by Alera. Do not edit.\r\namp --mode high < \"C:\\a b\\agent-prompt-s1.txt\"\r\n"
        );
    }

    #[test]
    fn the_prompt_file_holds_the_prompt_with_no_escaping_at_all() {
        let directory =
            std::env::temp_dir().join(format!("alera-agent-prompt-{}", uuid::Uuid::new_v4()));
        let prompt = "- Review $HOME\n- It's \"ready\"\n";
        let written =
            write_agent_prompt_stdin_script(&directory, "s 1", "amp", prompt).expect("write");
        assert_eq!(
            std::fs::read_to_string(&written.prompt_path).expect("read"),
            prompt
        );
        assert!(written
            .prompt_path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name == "agent-prompt-s_1.txt"));
        assert!(written.command.contains("agent-prompt-s_1"));
        std::fs::remove_dir_all(&directory).ok();
    }

    #[test]
    fn the_sweep_clears_both_generated_files_and_leaves_the_rest() {
        let directory =
            std::env::temp_dir().join(format!("alera-agent-prompt-sweep-{}", uuid::Uuid::new_v4()));
        let written =
            write_agent_prompt_stdin_script(&directory, "s1", "amp", "Ship it").expect("write");
        let unrelated = directory.join("control.json");
        std::fs::write(&unrelated, "{}").expect("write");
        remove_stale_agent_prompt_scripts(&directory);
        assert!(!written.script_path.exists());
        assert!(!written.prompt_path.exists());
        assert!(unrelated.exists());
        std::fs::remove_dir_all(&directory).ok();
    }
}
