// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> cancelWhisper({required String requestId}) =>
    RustLib.instance.api.crateApiAiDictationCancelWhisper(requestId: requestId);

Future<AiDictationResult> transcribeWhisper({
  required AiDictationRequest request,
}) =>
    RustLib.instance.api.crateApiAiDictationTranscribeWhisper(request: request);

class AiDictationError implements FrbException {
  final AiDictationErrorKind kind;
  final String message;

  const AiDictationError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiDictationError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum AiDictationErrorKind {
  invalidRequest,
  audio,
  model,
  cancelled,
  inference,
  io,
}

class AiDictationRequest {
  final String requestId;
  final String audioPath;
  final String modelPath;
  final String? language;
  final String? initialPrompt;

  const AiDictationRequest({
    required this.requestId,
    required this.audioPath,
    required this.modelPath,
    this.language,
    this.initialPrompt,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      audioPath.hashCode ^
      modelPath.hashCode ^
      language.hashCode ^
      initialPrompt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiDictationRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          audioPath == other.audioPath &&
          modelPath == other.modelPath &&
          language == other.language &&
          initialPrompt == other.initialPrompt;
}

class AiDictationResult {
  final String text;
  final String? detectedLanguage;
  final PlatformInt64 durationMillis;

  const AiDictationResult({
    required this.text,
    this.detectedLanguage,
    required this.durationMillis,
  });

  @override
  int get hashCode =>
      text.hashCode ^ detectedLanguage.hashCode ^ durationMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiDictationResult &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          detectedLanguage == other.detectedLanguage &&
          durationMillis == other.durationMillis;
}
