// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `content_token`, `copy_recursively`, `ensure_inside_existing_parent`, `ensure_not_descendant`, `entry_for_path`, `from_io`, `has_visible_child`, `ignored_aware_children`, `is_protected_child_path`, `is_protected_relative_path`, `join_relative`, `modified_millis`, `new`, `read_dir_children`, `reject_protected`, `relative_components`, `relative_string`, `resolve_existing_no_follow`, `resolve_existing`, `resolve_new_child`, `sanitize_name`, `unique_copy_destination`, `workspace_root`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<WorkspaceFileEntry>> listWorkspaceChildren({
  required String workspacePath,
  required String relativePath,
  required bool hideIgnored,
}) => RustLib.instance.api.crateApiWorkspaceFilesListWorkspaceChildren(
  workspacePath: workspacePath,
  relativePath: relativePath,
  hideIgnored: hideIgnored,
);

Future<WorkspaceQuickOpenSession> startWorkspaceQuickOpenSession({
  required String workspacePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesStartWorkspaceQuickOpenSession(
  workspacePath: workspacePath,
);

Future<List<WorkspaceQuickOpenMatch>> searchWorkspaceQuickOpenSession({
  required WorkspaceQuickOpenSession session,
  required String query,
  required int limit,
}) =>
    RustLib.instance.api.crateApiWorkspaceFilesSearchWorkspaceQuickOpenSession(
      session: session,
      query: query,
      limit: limit,
    );

Future<void> stopWorkspaceQuickOpenSession({
  required WorkspaceQuickOpenSession session,
}) => RustLib.instance.api.crateApiWorkspaceFilesStopWorkspaceQuickOpenSession(
  session: session,
);

Future<List<CodexSavedPrompt>> listCodexSavedPrompts({
  required String workspacePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesListCodexSavedPrompts(
  workspacePath: workspacePath,
);

Future<WorkspaceExplorerTreeProjection> projectWorkspaceExplorerTree({
  required String workspaceName,
  required String workspacePath,
  required List<WorkspaceExplorerDirectoryChildren> directories,
  WorkspaceExplorerDirectoryChildren? replacement,
}) => RustLib.instance.api.crateApiWorkspaceFilesProjectWorkspaceExplorerTree(
  workspaceName: workspaceName,
  workspacePath: workspacePath,
  directories: directories,
  replacement: replacement,
);

Future<WorkspaceExplorerWatcherHandle> startWorkspaceExplorerWatcher({
  required String workspacePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesStartWorkspaceExplorerWatcher(
  workspacePath: workspacePath,
);

Future<void> updateWorkspaceExplorerWatcher({
  required WorkspaceExplorerWatcherHandle handle,
  required List<String> watchedRelativePaths,
}) => RustLib.instance.api.crateApiWorkspaceFilesUpdateWorkspaceExplorerWatcher(
  handle: handle,
  watchedRelativePaths: watchedRelativePaths,
);

Stream<WorkspaceExplorerWatchBatch> watchWorkspaceExplorerEvents({
  required WorkspaceExplorerWatcherHandle handle,
}) => RustLib.instance.api.crateApiWorkspaceFilesWatchWorkspaceExplorerEvents(
  handle: handle,
);

Future<void> stopWorkspaceExplorerWatcher({
  required WorkspaceExplorerWatcherHandle handle,
}) => RustLib.instance.api.crateApiWorkspaceFilesStopWorkspaceExplorerWatcher(
  handle: handle,
);

Future<SourceControlWatcherHandle> startSourceControlWatcher({
  required String workspacePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesStartSourceControlWatcher(
  workspacePath: workspacePath,
);

Stream<SourceControlWatchSignal> watchSourceControlEvents({
  required SourceControlWatcherHandle handle,
}) => RustLib.instance.api.crateApiWorkspaceFilesWatchSourceControlEvents(
  handle: handle,
);

Future<void> stopSourceControlWatcher({
  required SourceControlWatcherHandle handle,
}) => RustLib.instance.api.crateApiWorkspaceFilesStopSourceControlWatcher(
  handle: handle,
);

Future<WorkspaceTextFile> readWorkspaceTextFile({
  required String workspacePath,
  required String relativePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesReadWorkspaceTextFile(
  workspacePath: workspacePath,
  relativePath: relativePath,
);

Future<WorkspaceEditorTextFile> readWorkspaceEditorTextFile({
  required String workspacePath,
  required String relativePath,
  required int tabSize,
}) => RustLib.instance.api.crateApiWorkspaceFilesReadWorkspaceEditorTextFile(
  workspacePath: workspacePath,
  relativePath: relativePath,
  tabSize: tabSize,
);

Future<WorkspaceTextFile> writeWorkspaceTextFile({
  required String workspacePath,
  required String relativePath,
  required String content,
  String? expectedContentToken,
  required bool overwriteIfChanged,
}) => RustLib.instance.api.crateApiWorkspaceFilesWriteWorkspaceTextFile(
  workspacePath: workspacePath,
  relativePath: relativePath,
  content: content,
  expectedContentToken: expectedContentToken,
  overwriteIfChanged: overwriteIfChanged,
);

Future<WorkspaceEditorTextFile> writeWorkspaceEditorTextFile({
  required String workspacePath,
  required String relativePath,
  required String currentDisplayContent,
  String? originalRawContent,
  String? originalDisplayContent,
  String? expectedContentToken,
  required bool overwriteIfChanged,
  required int tabSize,
}) => RustLib.instance.api.crateApiWorkspaceFilesWriteWorkspaceEditorTextFile(
  workspacePath: workspacePath,
  relativePath: relativePath,
  currentDisplayContent: currentDisplayContent,
  originalRawContent: originalRawContent,
  originalDisplayContent: originalDisplayContent,
  expectedContentToken: expectedContentToken,
  overwriteIfChanged: overwriteIfChanged,
  tabSize: tabSize,
);

Future<WorkspaceFileEntry> createWorkspaceFile({
  required String workspacePath,
  required String parentRelativePath,
  required String name,
}) => RustLib.instance.api.crateApiWorkspaceFilesCreateWorkspaceFile(
  workspacePath: workspacePath,
  parentRelativePath: parentRelativePath,
  name: name,
);

Future<WorkspaceFileEntry> createWorkspaceDirectory({
  required String workspacePath,
  required String parentRelativePath,
  required String name,
}) => RustLib.instance.api.crateApiWorkspaceFilesCreateWorkspaceDirectory(
  workspacePath: workspacePath,
  parentRelativePath: parentRelativePath,
  name: name,
);

Future<WorkspaceFileEntry> renameWorkspaceEntry({
  required String workspacePath,
  required String relativePath,
  required String newName,
}) => RustLib.instance.api.crateApiWorkspaceFilesRenameWorkspaceEntry(
  workspacePath: workspacePath,
  relativePath: relativePath,
  newName: newName,
);

Future<WorkspaceFileEntry> copyWorkspaceEntry({
  required String workspacePath,
  required String relativePath,
  required String targetParentRelativePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesCopyWorkspaceEntry(
  workspacePath: workspacePath,
  relativePath: relativePath,
  targetParentRelativePath: targetParentRelativePath,
);

Future<WorkspaceFileEntry> moveWorkspaceEntry({
  required String workspacePath,
  required String relativePath,
  required String targetParentRelativePath,
}) => RustLib.instance.api.crateApiWorkspaceFilesMoveWorkspaceEntry(
  workspacePath: workspacePath,
  relativePath: relativePath,
  targetParentRelativePath: targetParentRelativePath,
);

Future<void> deleteWorkspaceEntry({
  required String workspacePath,
  required String relativePath,
  required bool useTrash,
}) => RustLib.instance.api.crateApiWorkspaceFilesDeleteWorkspaceEntry(
  workspacePath: workspacePath,
  relativePath: relativePath,
  useTrash: useTrash,
);

class CodexSavedPrompt {
  final String name;
  final String description;
  final String? argumentHint;
  final String body;
  final CodexSavedPromptScope scope;

  const CodexSavedPrompt({
    required this.name,
    required this.description,
    this.argumentHint,
    required this.body,
    required this.scope,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      argumentHint.hashCode ^
      body.hashCode ^
      scope.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodexSavedPrompt &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          argumentHint == other.argumentHint &&
          body == other.body &&
          scope == other.scope;
}

enum CodexSavedPromptScope { user, repo }

class SourceControlWatchSignal {
  final int coalescedEventCount;

  const SourceControlWatchSignal({required this.coalescedEventCount});

  @override
  int get hashCode => coalescedEventCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceControlWatchSignal &&
          runtimeType == other.runtimeType &&
          coalescedEventCount == other.coalescedEventCount;
}

class SourceControlWatcherHandle {
  final String id;

  const SourceControlWatcherHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceControlWatcherHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class WorkspaceEditorTextFile {
  final String rawContent;
  final String displayContent;
  final String contentToken;
  final PlatformInt64 modifiedMillis;
  final BigInt size;

  const WorkspaceEditorTextFile({
    required this.rawContent,
    required this.displayContent,
    required this.contentToken,
    required this.modifiedMillis,
    required this.size,
  });

  @override
  int get hashCode =>
      rawContent.hashCode ^
      displayContent.hashCode ^
      contentToken.hashCode ^
      modifiedMillis.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceEditorTextFile &&
          runtimeType == other.runtimeType &&
          rawContent == other.rawContent &&
          displayContent == other.displayContent &&
          contentToken == other.contentToken &&
          modifiedMillis == other.modifiedMillis &&
          size == other.size;
}

class WorkspaceExplorerDirectoryChildren {
  final String relativePath;
  final List<WorkspaceFileEntry> children;

  const WorkspaceExplorerDirectoryChildren({
    required this.relativePath,
    required this.children,
  });

  @override
  int get hashCode => relativePath.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceExplorerDirectoryChildren &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          children == other.children;
}

class WorkspaceExplorerEntryBinding {
  final String nodeId;
  final String relativePath;

  const WorkspaceExplorerEntryBinding({
    required this.nodeId,
    required this.relativePath,
  });

  @override
  int get hashCode => nodeId.hashCode ^ relativePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceExplorerEntryBinding &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          relativePath == other.relativePath;
}

class WorkspaceExplorerTreeNode {
  final String id;
  final String name;
  final WorkspaceExplorerTreeNodeKind kind;
  final String parentId;
  final String virtualPath;
  final String sourcePath;
  final String? entryId;
  final List<String> childIds;
  final bool isExpanded;
  final bool isVirtual;

  const WorkspaceExplorerTreeNode({
    required this.id,
    required this.name,
    required this.kind,
    required this.parentId,
    required this.virtualPath,
    required this.sourcePath,
    this.entryId,
    required this.childIds,
    required this.isExpanded,
    required this.isVirtual,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      parentId.hashCode ^
      virtualPath.hashCode ^
      sourcePath.hashCode ^
      entryId.hashCode ^
      childIds.hashCode ^
      isExpanded.hashCode ^
      isVirtual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceExplorerTreeNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          parentId == other.parentId &&
          virtualPath == other.virtualPath &&
          sourcePath == other.sourcePath &&
          entryId == other.entryId &&
          childIds == other.childIds &&
          isExpanded == other.isExpanded &&
          isVirtual == other.isVirtual;
}

enum WorkspaceExplorerTreeNodeKind { root, folder, file }

class WorkspaceExplorerTreeProjection {
  final List<WorkspaceExplorerDirectoryChildren> directories;
  final List<WorkspaceExplorerTreeNode> nodes;
  final List<WorkspaceExplorerEntryBinding> entryBindings;

  const WorkspaceExplorerTreeProjection({
    required this.directories,
    required this.nodes,
    required this.entryBindings,
  });

  @override
  int get hashCode =>
      directories.hashCode ^ nodes.hashCode ^ entryBindings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceExplorerTreeProjection &&
          runtimeType == other.runtimeType &&
          directories == other.directories &&
          nodes == other.nodes &&
          entryBindings == other.entryBindings;
}

class WorkspaceExplorerWatchBatch {
  final List<String> directoryRelativePaths;
  final List<String> changedRelativePaths;
  final int coalescedEventCount;

  const WorkspaceExplorerWatchBatch({
    required this.directoryRelativePaths,
    required this.changedRelativePaths,
    required this.coalescedEventCount,
  });

  @override
  int get hashCode =>
      directoryRelativePaths.hashCode ^
      changedRelativePaths.hashCode ^
      coalescedEventCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceExplorerWatchBatch &&
          runtimeType == other.runtimeType &&
          directoryRelativePaths == other.directoryRelativePaths &&
          changedRelativePaths == other.changedRelativePaths &&
          coalescedEventCount == other.coalescedEventCount;
}

class WorkspaceExplorerWatcherHandle {
  final String id;

  const WorkspaceExplorerWatcherHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceExplorerWatcherHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class WorkspaceFileEntry {
  final String relativePath;
  final String name;
  final WorkspaceFileKind kind;
  final BigInt size;
  final PlatformInt64 modifiedMillis;
  final String contentToken;
  final bool isIgnored;
  final bool isHidden;
  final bool isSymlink;
  final bool isProtected;
  final bool hasChildrenHint;
  final WorkspaceFileGitStatus? gitStatus;

  const WorkspaceFileEntry({
    required this.relativePath,
    required this.name,
    required this.kind,
    required this.size,
    required this.modifiedMillis,
    required this.contentToken,
    required this.isIgnored,
    required this.isHidden,
    required this.isSymlink,
    required this.isProtected,
    required this.hasChildrenHint,
    this.gitStatus,
  });

  @override
  int get hashCode =>
      relativePath.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      size.hashCode ^
      modifiedMillis.hashCode ^
      contentToken.hashCode ^
      isIgnored.hashCode ^
      isHidden.hashCode ^
      isSymlink.hashCode ^
      isProtected.hashCode ^
      hasChildrenHint.hashCode ^
      gitStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceFileEntry &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          name == other.name &&
          kind == other.kind &&
          size == other.size &&
          modifiedMillis == other.modifiedMillis &&
          contentToken == other.contentToken &&
          isIgnored == other.isIgnored &&
          isHidden == other.isHidden &&
          isSymlink == other.isSymlink &&
          isProtected == other.isProtected &&
          hasChildrenHint == other.hasChildrenHint &&
          gitStatus == other.gitStatus;
}

class WorkspaceFileError implements FrbException {
  final WorkspaceFileErrorKind kind;
  final String context;

  const WorkspaceFileError({required this.kind, required this.context});

  @override
  int get hashCode => kind.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceFileError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          context == other.context;
}

enum WorkspaceFileErrorKind {
  invalidPath,
  outsideWorkspace,
  notFound,
  alreadyExists,
  protectedPath,
  unsupported,
  conflict,
  io,
}

enum WorkspaceFileGitStatus { untracked, added, modified }

enum WorkspaceFileKind { file, directory, symlink, other }

class WorkspaceQuickOpenMatch {
  final String relativePath;
  final int score;

  const WorkspaceQuickOpenMatch({
    required this.relativePath,
    required this.score,
  });

  @override
  int get hashCode => relativePath.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceQuickOpenMatch &&
          runtimeType == other.runtimeType &&
          relativePath == other.relativePath &&
          score == other.score;
}

class WorkspaceQuickOpenSession {
  final String id;
  final int indexedFileCount;

  const WorkspaceQuickOpenSession({
    required this.id,
    required this.indexedFileCount,
  });

  @override
  int get hashCode => id.hashCode ^ indexedFileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceQuickOpenSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          indexedFileCount == other.indexedFileCount;
}

class WorkspaceTextFile {
  final String content;
  final String contentToken;
  final PlatformInt64 modifiedMillis;
  final BigInt size;

  const WorkspaceTextFile({
    required this.content,
    required this.contentToken,
    required this.modifiedMillis,
    required this.size,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      contentToken.hashCode ^
      modifiedMillis.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceTextFile &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          contentToken == other.contentToken &&
          modifiedMillis == other.modifiedMillis &&
          size == other.size;
}
